dmaengine: sdxi: ioctl: Use %pa for printing physical address
When building for m68k:

  drivers/dma/sdxi/ioctl.c: In function 'sdxi_cxt_doorbell_mmap':
  drivers/dma/sdxi/ioctl.c:111:18: error: format '%llX' expects
    argument of type 'long long unsigned int', but argument 6 has type
    'phys_addr_t' {aka 'unsigned int'} [-Werror=format=]

Convert to %pa.

Signed-off-by: Nathan Lynch <nathan.lynch@amd.com>