dmaengine: sdxi: checkpatch error fixes (device.c)
Updates to match the rfc/v1 submission work in progress. Fix
checkpatch *errors*, leaving some warnings for now.

ERROR: do not initialise statics to false
+static bool dma_engine = false;

ERROR: do not initialise statics to false
+static bool set_pr_bits = false;

ERROR: do not initialise statics to false
+static bool force_pr_for_user_contexts = false;

ERROR: trailing whitespace
  #626: FILE: drivers/dma/sdxi/device.c:626:
+^I$

Signed-off-by: Nathan Lynch <nathan.lynch@amd.com>