dmaengine: sdxi: Address unused-but-set-variable warnings
When building with W=1:

  drivers/dma/sdxi/device.c:134:18: error: variable 'l1_idx' set but
  not used [-Werror,-Wunused-but-set-variable]
          u16 id, l2_idx, l1_idx;
                        ^
  drivers/dma/sdxi/device.c:170:18: error: variable 'l1_idx' set but
  not used [-Werror,-Wunused-but-set-variable]
          u16 id, l2_idx, l1_idx;

Remove the unneeded local variables 'l1_idx' and 'id' from
config_cxt_tables() and cleanup_cxt_tables().

Signed-off-by: Nathan Lynch <nathan.lynch@amd.com>