dmaengine: sdxi: Replace private MIN() macro with min()
Defining a custom MIN() macro breaks the build with clang:

drivers/dma/sdxi/pci.c:36:9: error: 'MIN' macro redefined
  [-Werror,-Wmacro-redefined]

Just use min() from minmax.h and coerce the bitfields to size_t.

Signed-off-by: Nathan Lynch <nathan.lynch@amd.com>
Fixes: eef3bf8415b5 ("SDXI: Add error log message")